# Generated by Django 4.2.7 on 2023-11-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='', verbose_name='Аудио файл')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['audio_file'],
            },
        ),
    ]
